In [8]:
import tensorflow as tf
import numpy as np
import tensorflow_datasets as tfds

In [9]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Define a function to increment numbers
def increment(x):
    return x + 1


# Use flat_map
flat_dataset = dataset.flat_map(
    lambda x: tf.data.Dataset.from_tensor_slices(increment(x))
)
for item in flat_dataset:
    print(item.numpy())

2
3
4
5
6
7
8
9
10


2024-05-27 23:02:55.253168: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [11]:
len(dataset)

3

In [10]:
# load a dataset
dataset = dataset.shuffle(buffer_size=len(dataset))

for item in dataset:
    print(item.numpy())

[4 5 6]
[7 8 9]
[1 2 3]


2024-05-27 23:03:15.033994: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
