In [1]:
import os

from language_table.environments import blocks
from language_table.environments import language_table
from language_table.environments.rewards import block2block

from matplotlib import pyplot as plt
import mediapy
import numpy as np
import tensorflow_datasets as tfds
from icecream import ic

np.set_printoptions(precision=3)

pybullet build time: Nov 28 2023 23:48:36
2024-06-04 04:37:21.422877: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-04 04:37:22.703012: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
# tf dataset handling
import tensorflow as tf

dataset = tf.data.Dataset.range(10)

for i in dataset:
    print(i)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


2024-06-04 04:37:28.611217: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-04 04:37:28.615647: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-04 04:37:28.770499: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required l

In [3]:
DATASET_PATH = "/data/language_table_sim"
builder = tfds.builder_from_directory(DATASET_PATH)
episode_ds = builder.as_dataset(split="train")
print(episode_ds.element_spec)

{'episode_id': TensorSpec(shape=(), dtype=tf.string, name=None), 'steps': DatasetSpec({'action': TensorSpec(shape=(2,), dtype=tf.float32, name=None), 'is_first': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_last': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_terminal': TensorSpec(shape=(), dtype=tf.bool, name=None), 'observation': {'effector_target_translation': TensorSpec(shape=(2,), dtype=tf.float32, name=None), 'effector_translation': TensorSpec(shape=(2,), dtype=tf.float32, name=None), 'instruction': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'rgb': TensorSpec(shape=(360, 640, 3), dtype=tf.uint8, name=None)}, 'reward': TensorSpec(shape=(), dtype=tf.float32, name=None)}, TensorShape([]))}


In [4]:
def decode_inst(inst):
    """Utility to decode encoded language instruction"""
    return bytes(inst[np.where(inst != 0)].tolist()).decode("utf-8")

In [5]:
def show_episode(episode):
    """Utility to visualize an episode"""
    print("Episode id:", episode["episode_id"].numpy())
    frames = []
    actions = []
    for step in episode["steps"].as_numpy_iterator():
        frames.append(step["observation"]["rgb"])
        actions.append(step["action"])

    print("step numbers: ", len(frames))
    mediapy.show_video(
        frames, title=decode_inst(step["observation"]["instruction"]), fps=5
    )
    # draw the action sequence
    actions = np.array(actions)
    actions.min(axis=0)
    print("action sequence:")
    print(actions)
    return actions.min(axis=0), actions.max(axis=0)

In [6]:
episodes_iter = iter(episode_ds.take(50))

# sample_episodes = tf.data.Dataset.sample_from_datasets(episode_ds)
# episodes_iter = iter(sample_episodes)
action_mins = []
action_maxes = []

for episode in episodes_iter:
    action_min, action_max = show_episode(episode)
    action_mins.append(action_min)
    action_maxes.append(action_max)

action_mins = np.array(action_mins)
action_maxes = np.array(action_maxes)

print("global action min:", action_mins.min(axis=0))
print("global action max:", action_maxes.max(axis=0))

Episode id: b'EiIKGHdvcmtlcl8wODlfZXBfOF8wNl8wNl8yMhAvGDggBDAAKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  10


2024-06-04 04:37:44.301217: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-3.057e-04  1.751e-02]
 [-7.094e-03  9.966e-03]
 [-1.165e-02  2.447e-03]
 [-1.404e-02 -7.375e-05]
 [-7.023e-03 -2.571e-03]
 [-4.685e-03 -2.567e-03]
 [ 8.861e-05 -5.076e-03]
 [-2.658e-04  1.523e-02]
 [-3.987e-04  2.284e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiMKGXdvcmtlcl8xMDZfZXBfMTBfMDZfMDZfMjIQORhrIA0wASogZjUyNTg1Mjg3YTE1NzZiODVkZmJjMjk5YjQ5ODExZmM='
step numbers:  51


2024-06-04 04:37:44.512544: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 6.346e-03 -2.051e-02]
 [ 2.439e-03 -1.746e-02]
 [ 6.199e-03 -1.724e-02]
 [ 7.302e-03 -1.817e-02]
 [ 6.014e-03 -7.483e-03]
 [ 4.722e-03 -7.435e-03]
 [ 8.158e-03 -4.483e-03]
 [ 9.116e-03  7.470e-04]
 [ 9.925e-03 -2.889e-03]
 [ 5.275e-03 -1.666e-02]
 [ 1.996e-03 -1.927e-02]
 [ 3.138e-03 -4.388e-03]
 [ 4.154e-03 -2.968e-03]
 [ 7.154e-03 -2.419e-03]
 [ 3.009e-03 -1.866e-03]
 [ 6.885e-03 -7.015e-03]
 [ 7.668e-03 -8.977e-03]
 [ 2.803e-03 -6.327e-03]
 [-7.228e-05 -1.036e-02]
 [-5.621e-05 -8.054e-03]
 [ 9.205e-04 -3.214e-03]
 [-1.604e-05 -2.297e-03]
 [ 8.018e-06  1.149e-03]
 [ 7.216e-05  1.034e-02]
 [-2.754e-03  1.203e-02]
 [-9.375e-04  2.108e-03]
 [-3.838e-03  3.554e-04]
 [-3.921e-03 -4.326e-03]
 [-2.033e-03 -9.824e-03]
 [-6.563e-05 -9.403e-03]
 [-1.022e-03 -4.952e-03]
 [-8.217e-06 -1.177e-03]
 [-8.217e-06 -1.177e-03]
 [ 9.727e-04 -2.096e-03]
 [ 9.613e-04 -3.263e-03]
 [ 9.581e-04 -3.252e-03]
 [ 9.631e-04 -2.072e-03]
 [ 9.436e-04 -4.400e-03]
 [ 9.731e-04  2.774e-04]
 [ 7.759

2024-06-04 04:37:44.718442: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-0.001 -0.006]
 [-0.002 -0.002]
 [-0.025 -0.006]
 [-0.002 -0.   ]
 [-0.012  0.014]
 [-0.017  0.002]
 [-0.013 -0.016]
 [-0.001 -0.017]
 [-0.002 -0.012]
 [ 0.004  0.002]
 [ 0.018  0.024]
 [ 0.008  0.016]
 [ 0.001  0.002]
 [ 0.004 -0.01 ]
 [-0.005 -0.023]
 [-0.008 -0.021]
 [-0.007 -0.016]
 [-0.002 -0.03 ]
 [-0.    -0.028]
 [ 0.003 -0.013]
 [ 0.002 -0.012]
 [ 0.003  0.004]
 [ 0.004  0.026]
 [ 0.007  0.013]
 [ 0.009  0.002]
 [ 0.007 -0.01 ]
 [ 0.002 -0.01 ]
 [-0.013 -0.027]
 [-0.009 -0.022]
 [-0.008 -0.029]
 [-0.005 -0.018]
 [ 0.     0.   ]]
Episode id: b'EiIKGHdvcmtlcl8wOThfZXBfN18wNV8yNV8yMhAsGDcgEDADKiAwNGYxNTRmYjRjNmM2YzkwNDE5M2NiMTlmNjRiNjRjNw=='


2024-06-04 04:37:44.898324: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  12


action sequence:
[[ 0.004 -0.03 ]
 [-0.009 -0.029]
 [-0.009 -0.028]
 [-0.009 -0.029]
 [-0.008 -0.029]
 [-0.015 -0.026]
 [-0.023 -0.019]
 [-0.015  0.003]
 [-0.006  0.018]
 [ 0.002  0.023]
 [ 0.002  0.009]
 [ 0.     0.   ]]
Episode id: b'EiQKGHdvcmtlcl8xMThfZXBfM18wNV8wOV8yMhCsAxjXAyAJMAQqIGIwMzEwNzBjZjRjZGYwYTJlODgzOWExM2JlZDRkN2Zk'
step numbers:  44


2024-06-04 04:37:45.030349: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 1.075e-02 -4.465e-03]
 [ 7.729e-03 -7.696e-03]
 [-5.581e-03 -6.651e-03]
 [-5.782e-03 -1.245e-02]
 [-7.127e-03 -1.401e-02]
 [-4.633e-03 -2.184e-02]
 [-3.035e-03 -1.431e-02]
 [ 2.797e-04 -3.000e-02]
 [-1.765e-03 -2.995e-02]
 [-1.758e-03 -1.486e-02]
 [-2.478e-03  1.897e-03]
 [-1.446e-02  2.628e-02]
 [-1.652e-02  1.898e-02]
 [-6.888e-03  2.712e-03]
 [-5.518e-03 -1.206e-02]
 [ 1.436e-03 -1.450e-02]
 [ 5.464e-03 -1.459e-02]
 [ 7.949e-03 -1.611e-02]
 [ 6.432e-03 -1.219e-02]
 [ 5.037e-03 -8.548e-03]
 [ 4.704e-03 -2.266e-02]
 [-7.749e-05 -4.698e-03]
 [ 1.185e-03 -3.164e-03]
 [ 1.177e-03 -3.144e-03]
 [ 2.424e-03 -1.629e-03]
 [ 2.408e-03 -1.619e-03]
 [ 2.393e-03 -1.609e-03]
 [ 2.378e-03 -1.599e-03]
 [ 3.478e-03 -4.639e-03]
 [ 3.435e-03 -4.581e-03]
 [ 2.313e-03 -1.541e-03]
 [ 1.080e-03 -2.984e-03]
 [-1.527e-02  7.824e-03]
 [-9.735e-03  1.782e-03]
 [-1.251e-02 -1.039e-02]
 [-3.774e-03 -4.497e-03]
 [ 2.467e-03 -6.067e-03]
 [ 4.921e-03 -3.030e-03]
 [ 2.437e-03 -1.501e-03]
 [ 4.829

2024-06-04 04:37:45.219694: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  11


action sequence:
[[ 8.333e-04 -1.250e-02]
 [ 1.708e-11 -1.000e-02]
 [-5.000e-03 -9.167e-03]
 [-1.250e-02 -8.334e-04]
 [-1.917e-02  8.333e-04]
 [-2.333e-02  1.083e-02]
 [-2.667e-02  1.250e-02]
 [-2.500e-02  1.167e-02]
 [-2.000e-02  9.167e-03]
 [-1.917e-02  1.333e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiIKGHdvcmtlcl8xMjVfZXBfMV8wNl8wNl8yMhAeGC4gAjAGKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  17


2024-06-04 04:37:45.380264: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-6.684e-03 -4.947e-09]
 [ 2.302e-02  2.971e-03]
 [ 2.863e-02  8.968e-03]
 [ 2.137e-02  2.106e-02]
 [-2.463e-02  1.713e-02]
 [-2.996e-02  1.590e-03]
 [-3.000e-02  2.537e-04]
 [-2.985e-02  2.974e-03]
 [-1.726e-02  1.497e-03]
 [ 2.228e-02  2.228e-03]
 [ 2.986e-02 -2.844e-03]
 [ 2.607e-02 -1.484e-02]
 [ 1.234e-02 -2.734e-02]
 [-2.918e-02 -6.973e-03]
 [-2.976e-02  3.756e-03]
 [-2.909e-02  7.322e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiQKGHdvcmtlcl8wNDFfZXBfMF8wNV8xN18yMhCRAhilAiAKMAcqIDc1ZGUxYmU0ZTUxNzBlNGI4YzYxMGY1OGM3NmI2NTAy'
step numbers:  21


2024-06-04 04:37:45.529921: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-1.381e-02  1.893e-03]
 [-8.568e-03  3.214e-04]
 [-1.030e-02 -3.938e-03]
 [-6.036e-03 -4.171e-03]
 [-1.538e-03 -2.874e-03]
 [-1.524e-03  3.235e-05]
 [-1.019e-05 -1.459e-03]
 [-3.088e-03 -2.872e-03]
 [-3.069e-05 -4.397e-03]
 [-4.093e-05 -5.863e-03]
 [-3.069e-05 -4.397e-03]
 [-1.544e-03 -8.074e-06]
 [ 6.268e-03  1.896e-02]
 [ 1.503e-02  1.965e-02]
 [ 1.007e-02  9.053e-04]
 [ 8.306e-03 -1.293e-02]
 [ 5.330e-03 -2.222e-02]
 [ 3.980e-03 -1.096e-02]
 [ 7.903e-03 -9.347e-03]
 [ 6.471e-03 -3.826e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiMKGXdvcmtlcl8xNTVfZXBfMTVfMDZfMDZfMjIQKhg5IAEwCCogZjUyNTg1Mjg3YTE1NzZiODVkZmJjMjk5YjQ5ODExZmM='
step numbers:  16


2024-06-04 04:37:45.685984: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 3.365e-10  2.031e-03]
 [-6.094e-03  8.802e-03]
 [-9.479e-03  7.448e-03]
 [-1.286e-02  7.448e-03]
 [-2.031e-03  6.771e-04]
 [-7.448e-03  2.708e-03]
 [-1.354e-02  4.740e-03]
 [-1.083e-02  4.062e-03]
 [-6.771e-04 -3.763e-09]
 [ 8.125e-03 -9.479e-03]
 [ 1.269e-02 -2.719e-02]
 [ 1.102e-02 -2.790e-02]
 [ 1.083e-02 -2.210e-02]
 [ 1.083e-02 -1.016e-02]
 [ 1.219e-02 -8.125e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiIKGHdvcmtlcl8wNTlfZXBfOF8wNl8wNl8yMhBOGHMgAjAJKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  38


2024-06-04 04:37:45.819035: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 1.951e-02  2.545e-03]
 [ 9.037e-03  1.252e-03]
 [ 7.307e-03 -4.359e-03]
 [ 3.630e-03 -2.165e-03]
 [ 1.471e-03 -2.203e-05]
 [ 4.952e-03 -6.368e-03]
 [ 1.632e-02 -1.126e-02]
 [ 2.051e-02 -9.310e-05]
 [ 7.069e-03  4.052e-03]
 [-1.852e-03  8.193e-03]
 [-8.029e-03  1.243e-02]
 [-6.850e-03  7.017e-03]
 [-6.967e-03  5.005e-03]
 [-1.071e-02  2.373e-03]
 [-7.315e-03 -1.893e-03]
 [-4.384e-03  1.170e-04]
 [-3.612e-03  2.203e-03]
 [-4.348e-03  2.938e-03]
 [-7.979e-03  7.313e-03]
 [-6.609e-03  5.197e-03]
 [-1.487e-03  7.658e-04]
 [-3.002e-03  8.240e-04]
 [-6.638e-03  7.403e-03]
 [-4.508e-03  3.058e-03]
 [-3.782e-03  2.321e-03]
 [-4.533e-03  3.807e-03]
 [-1.389e-03  5.838e-03]
 [-3.933e-04  1.374e-02]
 [-5.750e-04  7.259e-03]
 [-1.007e-04 -3.607e-03]
 [-1.595e-03 -1.351e-03]
 [-7.392e-03  1.569e-02]
 [-5.551e-03  2.736e-02]
 [ 1.830e-04  6.551e-03]
 [ 3.643e-03  1.716e-02]
 [ 4.251e-03  1.122e-02]
 [ 8.100e-05  2.900e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiQKGHdvcmtlcl8wNj

2024-06-04 04:37:45.988211: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 1.385e-02  1.094e-02]
 [ 1.240e-02 -7.293e-04]
 [ 7.292e-04 -7.292e-04]
 [ 1.345e-11 -1.458e-03]
 [ 3.646e-03 -1.021e-02]
 [ 1.458e-03 -8.750e-03]
 [ 5.104e-03 -9.479e-03]
 [ 4.375e-03 -1.021e-02]
 [ 5.833e-03 -1.823e-02]
 [ 2.917e-03 -1.094e-02]
 [-5.804e-11 -2.917e-03]
 [-7.292e-04 -3.646e-03]
 [ 5.947e-12 -1.458e-03]
 [ 0.000e+00 -8.021e-03]
 [ 5.551e-17 -7.292e-04]
 [-5.104e-03  2.092e-08]
 [-2.188e-03  8.964e-09]
 [ 2.917e-03 -8.021e-03]
 [ 7.292e-04 -5.104e-03]
 [ 1.848e-11 -3.646e-03]
 [-5.833e-03 -7.291e-04]
 [-5.833e-03  2.031e-08]
 [-1.458e-03  5.074e-09]
 [-7.292e-04 -1.458e-03]
 [ 7.292e-04 -5.104e-03]
 [ 2.188e-03 -1.094e-02]
 [-2.217e-11 -2.188e-03]
 [ 0.000e+00 -2.188e-03]
 [ 0.000e+00 -2.188e-03]
 [ 1.458e-03 -1.458e-03]
 [ 3.646e-03 -7.292e-03]
 [ 7.292e-04 -7.292e-04]
 [-3.646e-03 -7.292e-04]
 [-8.750e-03  2.917e-03]
 [-1.458e-03  7.292e-04]
 [-1.458e-03  7.292e-04]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiMKGHdvcmtlcl8xMzdfZXBfOV8wNV8yNV8yMhBtGIg

2024-06-04 04:37:46.159309: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  28


action sequence:
[[-8.034e-03 -2.890e-02]
 [-1.464e-02 -2.619e-02]
 [-1.462e-02 -2.620e-02]
 [-1.448e-02 -2.628e-02]
 [-8.116e-03 -2.888e-02]
 [-5.975e-03 -2.940e-02]
 [ 2.433e-04 -3.000e-02]
 [ 6.379e-03 -2.931e-02]
 [ 1.845e-02 -2.365e-02]
 [ 2.798e-02 -9.230e-03]
 [ 1.979e-02  1.781e-02]
 [ 7.917e-03  1.385e-02]
 [ 2.969e-03  1.089e-02]
 [ 9.046e-11  1.781e-02]
 [-2.969e-03  5.937e-03]
 [-8.906e-03  1.781e-02]
 [-6.927e-03  1.484e-02]
 [-1.385e-02  1.385e-02]
 [-5.937e-03  5.938e-03]
 [-1.583e-02  1.583e-02]
 [-4.948e-03  7.917e-03]
 [-3.958e-03  6.927e-03]
 [-6.927e-03  8.906e-03]
 [-7.917e-03  6.927e-03]
 [-7.917e-03  7.917e-03]
 [-1.188e-02  1.484e-02]
 [-9.896e-04  3.958e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiIKGHdvcmtlcl8xMjlfZXBfOV8wNV8yNV8yMhBMGHUgAzAMKiAwNGYxNTRmYjRjNmM2YzkwNDE5M2NiMTlmNjRiNjRjNw=='


2024-06-04 04:37:46.347285: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  42


action sequence:
[[ 8.529e-03  2.089e-02]
 [-3.679e-04  3.000e-02]
 [ 3.480e-04  3.000e-02]
 [ 5.608e-03  2.851e-02]
 [ 1.388e-02  1.004e-02]
 [ 9.469e-03  5.389e-04]
 [ 2.278e-02 -1.896e-03]
 [ 1.688e-02 -4.463e-03]
 [ 5.300e-03 -9.743e-03]
 [ 8.971e-04 -2.335e-02]
 [-1.100e-03 -1.377e-02]
 [-1.887e-03 -7.938e-03]
 [-2.652e-03 -3.144e-03]
 [-5.347e-04 -6.339e-04]
 [ 2.123e-05 -5.525e-04]
 [ 3.334e-03 -5.437e-05]
 [ 9.613e-03 -2.554e-02]
 [-9.471e-04 -2.919e-03]
 [-5.334e-03 -1.196e-03]
 [-3.840e-03 -3.057e-04]
 [-1.177e-02  9.352e-03]
 [-1.450e-02  2.626e-02]
 [-1.988e-02  1.428e-02]
 [-1.569e-02  6.141e-03]
 [-5.466e-03  8.518e-03]
 [ 5.176e-03 -9.663e-04]
 [ 1.975e-03 -1.372e-02]
 [-3.260e-03 -9.805e-03]
 [-1.118e-02 -1.868e-03]
 [-3.178e-03  2.265e-03]
 [-7.757e-03  2.898e-02]
 [-6.829e-03  1.845e-02]
 [-2.079e-03  1.138e-02]
 [-2.093e-03  1.146e-02]
 [-2.583e-05  6.724e-04]
 [ 3.070e-03 -1.549e-02]
 [ 2.022e-03 -1.002e-02]
 [-1.919e-02 -7.852e-03]
 [-2.188e-02 -3.470e-03]
 [-2.851

2024-06-04 04:37:46.557421: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 0.003 -0.018]
 [ 0.017 -0.025]
 [ 0.011 -0.008]
 [ 0.014 -0.011]
 [ 0.011 -0.006]
 [ 0.001 -0.001]
 [-0.003  0.004]
 [-0.014  0.015]
 [-0.007  0.01 ]
 [-0.007  0.01 ]
 [-0.013  0.012]
 [-0.02  -0.01 ]
 [-0.02  -0.022]
 [ 0.004 -0.03 ]
 [ 0.012 -0.017]
 [ 0.023 -0.002]
 [ 0.014  0.005]
 [ 0.012  0.005]
 [ 0.013  0.004]
 [ 0.012  0.01 ]
 [ 0.004  0.005]
 [-0.017 -0.004]
 [-0.028  0.004]
 [ 0.     0.   ]]
Episode id: b'EiIKGHdvcmtlcl8wNDFfZXBfMl8wNV8wOV8yMhAvGD4gATAOKiBiMDMxMDcwY2Y0Y2RmMGEyZTg4MzlhMTNiZWQ0ZDdmZA=='
step numbers:  16


2024-06-04 04:37:46.728556: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 0.007  0.002]
 [ 0.013  0.005]
 [ 0.015 -0.006]
 [-0.015 -0.008]
 [-0.029 -0.007]
 [-0.014 -0.005]
 [-0.025 -0.017]
 [-0.006 -0.004]
 [-0.003 -0.002]
 [ 0.01   0.023]
 [ 0.003  0.015]
 [-0.002  0.005]
 [-0.006  0.007]
 [-0.005  0.004]
 [-0.008  0.001]
 [ 0.     0.   ]]
Episode id: b'EiMKGHdvcmtlcl8xMzZfZXBfMl8wNl8wNl8yMhBiGJQBIBcwDyogZjUyNTg1Mjg3YTE1NzZiODVkZmJjMjk5YjQ5ODExZmM='
step numbers:  51


2024-06-04 04:37:46.862323: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 0.026 -0.01 ]
 [ 0.022 -0.02 ]
 [ 0.02  -0.022]
 [ 0.014 -0.021]
 [ 0.008 -0.017]
 [ 0.003 -0.014]
 [ 0.001 -0.009]
 [-0.007 -0.011]
 [-0.02  -0.02 ]
 [-0.024 -0.011]
 [ 0.002 -0.001]
 [ 0.015 -0.003]
 [ 0.011 -0.028]
 [-0.004 -0.021]
 [-0.014 -0.013]
 [-0.02   0.005]
 [-0.02   0.01 ]
 [-0.017  0.009]
 [-0.001  0.002]
 [ 0.022 -0.011]
 [ 0.029  0.008]
 [ 0.015  0.014]
 [-0.004  0.009]
 [-0.013  0.009]
 [-0.028  0.011]
 [-0.02  -0.001]
 [-0.024 -0.009]
 [-0.026 -0.015]
 [-0.024 -0.017]
 [-0.005 -0.004]
 [ 0.007  0.004]
 [ 0.021  0.021]
 [ 0.002  0.01 ]
 [-0.003  0.017]
 [-0.006  0.011]
 [-0.012  0.004]
 [-0.022 -0.016]
 [-0.019 -0.023]
 [-0.012 -0.019]
 [-0.004 -0.01 ]
 [-0.003 -0.008]
 [ 0.001 -0.004]
 [ 0.005  0.006]
 [ 0.011  0.008]
 [ 0.001  0.001]
 [ 0.001  0.001]
 [ 0.028  0.012]
 [ 0.006  0.001]
 [ 0.022  0.014]
 [ 0.026  0.005]
 [ 0.     0.   ]]
Episode id: b'EiQKGXdvcmtlcl8wNDlfZXBfMTRfMDZfMDZfMjIQWRhsIAIw6AcqIGY1MjU4NTI4N2ExNTc2Yjg1ZGZiYzI5OWI0OTgxMWZj'
ste

2024-06-04 04:37:47.063940: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 1.381e-02 -1.658e-03]
 [ 1.083e-02  7.936e-03]
 [ 5.420e-03  1.807e-02]
 [-7.404e-04  2.999e-02]
 [-1.066e-03  2.998e-02]
 [-9.097e-04  2.398e-02]
 [ 5.683e-04 -1.345e-02]
 [-2.185e-03 -2.806e-02]
 [-8.148e-03 -1.498e-02]
 [-1.448e-02 -9.493e-03]
 [-1.775e-02  2.692e-04]
 [-6.470e-03  1.163e-02]
 [ 5.282e-03  2.565e-02]
 [ 9.624e-03  2.841e-02]
 [ 8.562e-03  2.696e-02]
 [ 4.328e-03  2.183e-02]
 [ 2.225e-03  2.155e-02]
 [ 8.486e-04  2.281e-02]
 [ 2.891e-05  4.142e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiUKGHdvcmtlcl8wNjRfZXBfNF8wNV8xN18yMhCrARi8ASAGMOkHKiA3NWRlMWJlNGU1MTcwZTRiOGM2MTBmNThjNzZiNjUwMg=='
step numbers:  18


2024-06-04 04:37:47.232354: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-0.004  0.002]
 [-0.005  0.002]
 [-0.007  0.004]
 [-0.004  0.002]
 [-0.005  0.003]
 [-0.008  0.001]
 [-0.009 -0.001]
 [-0.004 -0.003]
 [-0.006 -0.002]
 [-0.004 -0.001]
 [-0.01   0.002]
 [-0.009  0.003]
 [-0.014  0.007]
 [-0.01   0.005]
 [-0.009  0.004]
 [-0.007  0.002]
 [-0.004  0.002]
 [ 0.     0.   ]]
Episode id: b'EiMKGHdvcmtlcl8xNzBfZXBfMl8wNV8xN18yMhA4GD0gATDqByogNzVkZTFiZTRlNTE3MGU0YjhjNjEwZjU4Yzc2YjY1MDI='
step numbers:  6


2024-06-04 04:37:47.363792: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-0.002 -0.012]
 [-0.004 -0.01 ]
 [-0.01  -0.017]
 [-0.012 -0.017]
 [-0.006 -0.011]
 [ 0.     0.   ]]
Episode id: b'EiMKGHdvcmtlcl8wNDhfZXBfMV8wNV8xN18yMhBGGGYgAjDrByogNzVkZTFiZTRlNTE3MGU0YjhjNjEwZjU4Yzc2YjY1MDI='
step numbers:  33


2024-06-04 04:37:47.506758: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 1.251e-09  5.222e-03]
 [ 1.846e-09  8.704e-03]
 [-1.626e-03  1.372e-02]
 [ 1.508e-09  6.972e-03]
 [-1.630e-03  1.548e-03]
 [-1.635e-03  1.552e-03]
 [ 1.833e-09  8.739e-03]
 [ 1.853e-09  8.739e-03]
 [ 3.707e-10  1.748e-03]
 [ 6.512e-03 -1.150e-02]
 [ 1.912e-02 -1.496e-02]
 [ 1.395e-02  5.151e-03]
 [ 7.609e-03  7.662e-03]
 [ 1.630e-09  6.719e-03]
 [-1.514e-03  6.558e-03]
 [-9.167e-03  1.258e-02]
 [-6.192e-03  6.227e-03]
 [-1.099e-02  9.337e-03]
 [-3.179e-03  3.192e-03]
 [ 1.591e-03  1.846e-03]
 [ 2.766e-02 -1.162e-02]
 [ 1.672e-02 -2.147e-02]
 [ 4.403e-03 -1.935e-02]
 [-1.331e-02 -8.354e-03]
 [ 8.190e-03 -2.886e-02]
 [ 1.215e-02 -2.743e-02]
 [ 2.565e-02 -1.471e-02]
 [ 1.632e-02  8.013e-03]
 [-9.348e-03  2.851e-02]
 [-1.502e-02  2.597e-02]
 [-7.344e-03  9.268e-03]
 [-1.420e-03 -1.485e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiUKGHdvcmtlcl8wNjFfZXBfMV8wNl8wNl8yMhC4ARjjASAFMOwHKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='


2024-06-04 04:37:47.695488: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  44


2024-06-04 04:37:47.872737: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-8.516e-04  4.024e-03]
 [ 1.264e-02  7.615e-03]
 [ 8.265e-03  3.167e-03]
 [ 5.712e-03 -1.289e-03]
 [ 3.237e-03 -2.602e-03]
 [-7.069e-10  3.083e-03]
 [-1.472e-02  1.071e-02]
 [ 1.633e-02  2.230e-03]
 [ 1.272e-02  2.151e-02]
 [-1.111e-02  1.751e-02]
 [-9.711e-03  7.554e-03]
 [-1.239e-02  3.364e-03]
 [-2.989e-02  2.547e-03]
 [-2.448e-02  3.768e-03]
 [-2.062e-02 -2.877e-03]
 [-5.752e-03 -4.248e-03]
 [-9.642e-04 -3.240e-03]
 [ 3.847e-03 -1.815e-02]
 [ 1.049e-02 -2.811e-02]
 [ 7.445e-03 -2.612e-02]
 [ 1.856e-03 -1.170e-02]
 [ 5.533e-03 -2.254e-02]
 [ 2.746e-03 -8.317e-03]
 [-1.668e-02  1.308e-02]
 [-1.524e-02  1.672e-02]
 [-6.794e-03 -4.381e-04]
 [-2.086e-02 -1.170e-02]
 [ 8.112e-10 -1.725e-03]
 [ 1.003e-02 -1.930e-02]
 [ 9.860e-03 -1.643e-02]
 [ 1.449e-02 -6.964e-03]
 [ 1.692e-02 -7.639e-03]
 [ 1.101e-02 -3.335e-03]
 [ 1.815e-03 -1.639e-03]
 [-1.815e-03 -5.723e-03]
 [-2.733e-03 -8.209e-03]
 [ 2.733e-03 -9.786e-03]
 [ 1.258e-02 -7.845e-03]
 [ 1.057e-02 -2.925e-03]
 [-9.436

action sequence:
[[ 7.910e-03  9.426e-03]
 [ 1.977e-03  2.357e-03]
 [ 2.009e-03  3.562e-03]
 [ 4.232e-03  1.331e-02]
 [ 9.522e-04  9.591e-03]
 [-3.085e-03  6.222e-03]
 [-4.551e-03  4.734e-03]
 [-3.993e-03  4.350e-03]
 [-2.727e-03  2.051e-03]
 [-2.763e-03  2.078e-03]
 [-2.097e-03  1.577e-03]
 [-1.375e-03  6.639e-03]
 [ 7.411e-04  3.680e-03]
 [-6.874e-04  4.832e-03]
 [ 1.815e-05  2.877e-03]
 [-1.435e-03  4.059e-03]
 [-2.196e-03  3.233e-03]
 [-1.481e-03  2.677e-03]
 [-7.461e-04  6.020e-04]
 [-7.487e-04  6.041e-04]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiMKGHdvcmtlcl8xMTZfZXBfMl8wNV8yNV8yMhBYGGEgEDDuByogMDRmMTU0ZmI0YzZjNmM5MDQxOTNjYjE5ZjY0YjY0Yzc='
step numbers:  10


2024-06-04 04:37:48.047016: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[9.115e-03 1.563e-02]
 [1.042e-02 1.693e-02]
 [7.812e-03 1.302e-02]
 [1.302e-03 1.823e-02]
 [6.510e-03 1.432e-02]
 [3.906e-03 1.302e-02]
 [1.302e-03 1.823e-02]
 [3.906e-03 2.865e-02]
 [8.220e-11 1.302e-03]
 [0.000e+00 0.000e+00]]
Episode id: b'EiYKGXdvcmtlcl8wNzJfZXBfMTBfMDZfMDZfMjIQhAEYlAEgCDDvByogZjUyNTg1Mjg3YTE1NzZiODVkZmJjMjk5YjQ5ODExZmM='
step numbers:  17


2024-06-04 04:37:48.162389: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 0.000e+00 -1.770e-02]
 [ 0.000e+00 -7.079e-03]
 [ 5.551e-17 -3.540e-03]
 [-1.988e-03 -1.237e-02]
 [ 7.899e-03 -1.237e-02]
 [ 7.764e-03 -6.928e-03]
 [ 1.140e-02 -1.706e-02]
 [ 5.593e-03 -3.237e-03]
 [ 2.345e-02  4.192e-03]
 [ 1.041e-02  1.021e-02]
 [ 3.413e-03  1.318e-02]
 [ 1.696e-03  1.309e-02]
 [ 2.414e-11  1.308e-02]
 [-3.399e-03  6.652e-03]
 [-1.212e-02  1.705e-02]
 [-1.066e-02  1.236e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiMKGHdvcmtlcl8xNDZfZXBfNF8wNV8yNV8yMhAeGD4gATDwByogMDRmMTU0ZmI0YzZjNmM5MDQxOTNjYjE5ZjY0YjY0Yzc='
step numbers:  33


2024-06-04 04:37:48.301521: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-6.857e-03 -3.967e-03]
 [-9.542e-03 -7.142e-03]
 [-2.645e-03 -3.153e-03]
 [-3.968e-03 -4.729e-03]
 [-2.645e-03 -3.153e-03]
 [-1.780e-02  2.919e-04]
 [-2.607e-02  9.662e-05]
 [-1.162e-02  4.538e-03]
 [-4.156e-03 -4.953e-03]
 [-3.389e-03 -2.243e-02]
 [ 1.790e-03 -2.466e-02]
 [ 6.530e-03 -1.385e-02]
 [ 1.248e-02 -1.440e-02]
 [ 3.477e-03 -4.012e-03]
 [ 1.108e-02 -6.798e-03]
 [-8.915e-03  2.578e-02]
 [-1.237e-02  2.733e-02]
 [-8.596e-03  1.713e-02]
 [-5.173e-04  3.941e-03]
 [ 8.732e-03  5.850e-03]
 [ 1.412e-02 -1.132e-03]
 [ 1.897e-02 -7.848e-03]
 [ 8.071e-03 -7.249e-03]
 [ 6.261e-03 -4.944e-03]
 [ 4.868e-03 -6.399e-03]
 [ 2.539e-03 -1.293e-02]
 [-1.276e-03 -1.521e-03]
 [ 1.890e-03 -5.596e-03]
 [-2.851e-03  5.158e-04]
 [-1.724e-02  1.565e-02]
 [-6.911e-03 -4.101e-03]
 [-1.360e-04 -1.250e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiYKGXdvcmtlcl8xMzVfZXBfMTBfMDZfMDZfMjIQ0gEY8AEgBTDxByogZjUyNTg1Mjg3YTE1NzZiODVkZmJjMjk5YjQ5ODExZmM='


2024-06-04 04:37:48.487662: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  31


action sequence:
[[ 0.008  0.004]
 [ 0.007 -0.007]
 [ 0.005 -0.014]
 [-0.001 -0.03 ]
 [-0.009 -0.02 ]
 [-0.015 -0.026]
 [-0.019 -0.023]
 [-0.001 -0.002]
 [ 0.019  0.018]
 [ 0.026  0.015]
 [ 0.028 -0.011]
 [ 0.016 -0.022]
 [ 0.005 -0.029]
 [-0.012 -0.011]
 [-0.03   0.001]
 [-0.028  0.011]
 [-0.023  0.013]
 [ 0.005 -0.003]
 [ 0.014 -0.013]
 [ 0.006 -0.01 ]
 [ 0.    -0.004]
 [-0.004 -0.001]
 [-0.015  0.003]
 [-0.016  0.006]
 [-0.005  0.003]
 [-0.003  0.001]
 [ 0.016  0.019]
 [ 0.011  0.028]
 [ 0.005  0.03 ]
 [-0.002  0.03 ]
 [ 0.     0.   ]]
Episode id: b'EiUKGHdvcmtlcl8wNTRfZXBfN18wNl8wNl8yMhDUARjgASAFMPIHKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  13


2024-06-04 04:37:48.638985: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 5.780e-04 -1.331e-03]
 [ 6.751e-04  4.275e-03]
 [ 3.145e-03  8.878e-03]
 [ 3.640e-03  4.395e-03]
 [ 2.450e-03  5.172e-03]
 [ 6.457e-05  3.700e-03]
 [-3.458e-03  4.936e-03]
 [-5.897e-03  4.159e-03]
 [-6.018e-03  1.706e-03]
 [-3.689e-03 -1.233e-03]
 [-4.336e-03 -1.134e-03]
 [-1.901e-03 -2.210e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiYKGXdvcmtlcl8xMzNfZXBfMTBfMDZfMDZfMjIQ2QEYggIgBTDzByogZjUyNTg1Mjg3YTE1NzZiODVkZmJjMjk5YjQ5ODExZmM='
step numbers:  42


2024-06-04 04:37:48.781150: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


2024-06-04 04:37:48.977541: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-8.021e-03 -5.833e-03]
 [-2.220e-02 -2.018e-02]
 [-2.028e-02 -2.211e-02]
 [-4.923e-03 -8.021e-03]
 [-6.563e-03 -8.021e-03]
 [-2.032e-02 -2.207e-02]
 [-2.050e-02 -2.190e-02]
 [-1.095e-02 -1.655e-02]
 [-3.646e-03 -8.750e-03]
 [-7.292e-04 -8.021e-03]
 [-1.181e-11 -2.625e-02]
 [ 3.646e-03 -1.750e-02]
 [ 1.094e-02 -3.646e-03]
 [ 2.042e-02  5.104e-03]
 [ 9.479e-03  5.833e-03]
 [ 6.563e-03  6.563e-03]
 [ 8.021e-03  8.021e-03]
 [ 1.094e-02  9.479e-03]
 [ 1.750e-02  1.458e-02]
 [ 2.042e-02  1.385e-02]
 [ 9.479e-03  4.375e-03]
 [ 2.800e-02  1.077e-02]
 [ 3.354e-03  8.973e-04]
 [-2.917e-03 -9.479e-03]
 [-2.187e-03 -6.563e-03]
 [ 7.292e-03 -5.833e-03]
 [ 2.333e-02 -5.833e-03]
 [ 2.951e-02  5.420e-03]
 [ 2.008e-02  9.164e-03]
 [-7.292e-04  3.646e-03]
 [-8.750e-03  9.479e-03]
 [-3.646e-03  5.104e-03]
 [-7.292e-04  2.187e-03]
 [-7.292e-04  4.375e-03]
 [-4.375e-03  2.187e-03]
 [-8.750e-03 -2.917e-03]
 [-1.458e-03 -1.458e-03]
 [-3.646e-03  8.750e-03]
 [ 1.458e-03  2.042e-02]
 [ 2.187

action sequence:
[[ 7.473e-03  6.306e-03]
 [ 5.864e-03  8.827e-03]
 [-2.170e-05  6.216e-03]
 [ 2.887e-03  7.781e-03]
 [ 4.292e-03  1.122e-02]
 [-1.443e-03  1.301e-03]
 [-2.393e-06  6.856e-04]
 [-2.169e-03  5.875e-04]
 [-1.029e-02  3.715e-03]
 [ 7.260e-04  4.901e-03]
 [-7.698e-04  7.638e-03]
 [-7.469e-04  6.795e-04]
 [ 1.531e-03 -1.249e-02]
 [ 5.194e-03 -8.786e-03]
 [ 1.791e-02 -4.499e-03]
 [ 2.787e-03  1.607e-04]
 [ 4.805e-03  6.965e-03]
 [ 5.404e-03  1.155e-02]
 [ 4.687e-03  3.457e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiUKGHdvcmtlcl8xNzhfZXBfMV8wNl8wNl8yMhDTAhjyAiAVMPUHKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  32


2024-06-04 04:37:49.145596: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 7.292e-04  2.188e-03]
 [ 1.458e-03  7.292e-03]
 [ 7.292e-04 -1.458e-03]
 [ 7.292e-04 -1.385e-02]
 [ 2.833e-11 -1.823e-02]
 [-5.104e-03 -1.750e-02]
 [-7.292e-04 -6.563e-03]
 [-7.292e-04 -7.292e-04]
 [-1.458e-03 -1.458e-03]
 [-7.292e-03 -5.833e-03]
 [-6.563e-03 -3.646e-03]
 [-5.104e-03 -1.351e-08]
 [-2.188e-03 -5.806e-09]
 [ 7.292e-04  5.104e-03]
 [ 5.104e-03  2.479e-02]
 [ 7.292e-04  8.021e-03]
 [ 1.614e-11  3.646e-03]
 [ 0.000e+00  7.292e-04]
 [-7.292e-03 -4.375e-03]
 [-8.021e-03 -1.167e-02]
 [-6.563e-03 -5.833e-03]
 [-1.458e-03 -1.458e-03]
 [-1.458e-03 -2.188e-03]
 [ 2.917e-03 -1.313e-02]
 [ 7.246e-11 -5.833e-03]
 [-4.375e-03 -4.375e-03]
 [-2.917e-03 -8.206e-09]
 [-1.750e-02  4.375e-03]
 [-9.479e-03  2.187e-03]
 [-5.833e-03  3.646e-03]
 [-7.292e-04  7.292e-04]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiQKGHdvcmtlcl8wMTNfZXBfNF8wNV8xN18yMhBvGJUBIAUw9gcqIDc1ZGUxYmU0ZTUxNzBlNGI4YzYxMGY1OGM3NmI2NTAy'


2024-06-04 04:37:49.316977: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  39


2024-06-04 04:37:49.498388: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-0.001 -0.015]
 [ 0.012  0.027]
 [ 0.002  0.03 ]
 [-0.003  0.03 ]
 [-0.001  0.005]
 [ 0.002  0.002]
 [ 0.028 -0.008]
 [ 0.022 -0.019]
 [ 0.006 -0.004]
 [ 0.003 -0.002]
 [ 0.006 -0.007]
 [-0.001 -0.006]
 [-0.01  -0.009]
 [-0.025 -0.017]
 [-0.012 -0.009]
 [-0.001 -0.001]
 [-0.002 -0.005]
 [ 0.026  0.004]
 [ 0.022 -0.021]
 [ 0.005 -0.014]
 [-0.017 -0.024]
 [-0.017 -0.025]
 [-0.017 -0.025]
 [-0.017 -0.025]
 [-0.025 -0.016]
 [-0.03  -0.003]
 [-0.03   0.004]
 [-0.028  0.011]
 [-0.026  0.015]
 [-0.007  0.005]
 [ 0.005  0.006]
 [ 0.017  0.006]
 [ 0.007 -0.   ]
 [ 0.022 -0.01 ]
 [ 0.003  0.001]
 [ 0.004  0.003]
 [ 0.01   0.009]
 [ 0.002  0.002]
 [ 0.     0.   ]]
Episode id: b'EiMKGHdvcmtlcl8wMDNfZXBfNl8wNl8wNl8yMhASGBggBTD3ByogZjUyNTg1Mjg3YTE1NzZiODVkZmJjMjk5YjQ5ODExZmM='
step numbers:  7


action sequence:
[[ 0.002 -0.   ]
 [ 0.    -0.002]
 [ 0.003 -0.017]
 [ 0.016 -0.017]
 [ 0.02   0.001]
 [ 0.01   0.01 ]
 [ 0.     0.   ]]
Episode id: b'EiQKGHdvcmtlcl8xNDZfZXBfOV8wNV8yNV8yMhDqAhiTAyAJMAAqIDA0ZjE1NGZiNGM2YzZjOTA0MTkzY2IxOWY2NGI2NGM3'
step numbers:  42


2024-06-04 04:37:49.634491: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-1.005e-03 -1.269e-02]
 [-3.163e-03 -1.225e-02]
 [-4.266e-03 -7.886e-03]
 [-5.369e-03 -6.399e-03]
 [-2.148e-03 -2.560e-03]
 [-3.285e-03 -1.114e-03]
 [-4.305e-03 -5.131e-03]
 [-7.626e-03 -6.273e-03]
 [-3.336e-03 -1.148e-03]
 [-1.363e-02 -1.908e-03]
 [-5.909e-03  1.722e-03]
 [-1.243e-02  9.175e-03]
 [-1.306e-03  1.507e-03]
 [ 7.416e-03 -3.328e-03]
 [ 1.563e-02 -7.911e-03]
 [ 8.269e-03 -7.230e-03]
 [ 4.950e-03 -1.345e-02]
 [ 9.038e-05 -2.606e-03]
 [-1.688e-02  1.942e-03]
 [-2.007e-02  4.829e-03]
 [-1.292e-02  1.165e-02]
 [-1.094e-02  1.201e-02]
 [-1.398e-03  1.534e-03]
 [ 5.316e-03 -3.218e-03]
 [ 2.723e-02 -1.259e-02]
 [ 1.144e-02 -1.017e-02]
 [ 4.003e-04 -7.967e-03]
 [-5.369e-03 -6.399e-03]
 [-2.286e-02 -7.356e-03]
 [-1.832e-02  1.708e-03]
 [-2.398e-02  1.164e-02]
 [-1.889e-02  1.358e-02]
 [-9.444e-03  9.285e-03]
 [ 6.328e-03 -6.221e-03]
 [ 1.527e-02 -1.502e-02]
 [ 1.814e-03 -4.286e-03]
 [-1.987e-02  9.210e-03]
 [-2.161e-02  2.080e-02]
 [-1.837e-02  1.768e-02]
 [-1.778

2024-06-04 04:37:49.816677: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  32


action sequence:
[[-2.884e-02 -8.264e-03]
 [-2.998e-02 -1.193e-03]
 [-2.912e-02  7.219e-03]
 [-2.797e-02  1.085e-02]
 [-1.131e-02  2.778e-02]
 [ 2.116e-03  2.993e-02]
 [ 1.111e-02  2.787e-02]
 [ 1.121e-02  1.306e-02]
 [ 1.250e-02 -1.886e-08]
 [ 1.833e-02 -1.250e-02]
 [ 1.083e-02 -1.000e-02]
 [ 1.500e-02 -5.833e-03]
 [ 2.869e-02 -8.767e-03]
 [ 2.131e-02 -5.400e-03]
 [ 1.750e-02 -1.667e-03]
 [ 3.333e-03 -4.861e-10]
 [-1.500e-02  6.667e-03]
 [-1.833e-02  1.500e-02]
 [-1.218e-02  2.741e-02]
 [-7.552e-03  2.903e-02]
 [-6.074e-03  2.938e-02]
 [-2.992e-03  2.985e-02]
 [ 4.102e-03  2.972e-02]
 [ 1.173e-02  2.761e-02]
 [ 1.736e-02  2.447e-02]
 [ 1.846e-02  2.365e-02]
 [ 2.702e-02  1.303e-02]
 [ 1.347e-02 -1.916e-02]
 [ 1.667e-03 -6.667e-03]
 [-2.441e-11 -4.167e-03]
 [-6.667e-03 -2.167e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiQKGHdvcmtlcl8wMTBfZXBfOV8wNV8yNV8yMhDcARjqASAUMAIqIDA0ZjE1NGZiNGM2YzZjOTA0MTkzY2IxOWY2NGI2NGM3'
step numbers:  15


2024-06-04 04:37:49.972720: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 0.014  0.004]
 [ 0.011 -0.005]
 [ 0.004 -0.003]
 [-0.002  0.009]
 [-0.001  0.004]
 [ 0.001  0.013]
 [ 0.002  0.01 ]
 [ 0.005 -0.001]
 [ 0.004 -0.004]
 [-0.009 -0.014]
 [-0.016 -0.01 ]
 [-0.015 -0.013]
 [-0.012 -0.014]
 [-0.002 -0.018]
 [ 0.     0.   ]]
Episode id: b'EiIKGHdvcmtlcl8xMTNfZXBfOV8wNl8wNl8yMhBTGF8gDjADKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  13


2024-06-04 04:37:50.110726: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 0.001 -0.007]
 [ 0.01  -0.01 ]
 [ 0.01  -0.009]
 [ 0.011 -0.017]
 [ 0.006 -0.008]
 [ 0.003 -0.001]
 [ 0.002  0.004]
 [-0.006  0.022]
 [-0.001  0.008]
 [ 0.009  0.002]
 [ 0.01  -0.017]
 [ 0.015 -0.016]
 [ 0.     0.   ]]
Episode id: b'EiQKGHdvcmtlcl8xMjlfZXBfM18wNV8wOV8yMhDqARj1ASAVMAQqIGIwMzEwNzBjZjRjZGYwYTJlODgzOWExM2JlZDRkN2Zk'
step numbers:  12


2024-06-04 04:37:50.248663: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-2.018e-03 -1.664e-03]
 [-1.011e-03 -8.339e-04]
 [-2.058e-03 -2.538e-03]
 [-1.974e-03  5.617e-05]
 [-5.024e-03 -1.601e-03]
 [-4.061e-03 -1.640e-03]
 [-1.015e-02 -6.223e-04]
 [-1.224e-02  3.867e-03]
 [-9.625e-03  2.841e-02]
 [ 6.236e-04  2.999e-02]
 [ 3.190e-03  2.983e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiQKGHdvcmtlcl8xMDlfZXBfN18wNl8wNl8yMhDNAhj8AiASMAUqIGY1MjU4NTI4N2ExNTc2Yjg1ZGZiYzI5OWI0OTgxMWZj'
step numbers:  48


2024-06-04 04:37:50.406264: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-2.156e-02 -1.030e-04]
 [-1.293e-02 -1.213e-03]
 [-9.393e-03  4.437e-04]
 [-1.203e-02  9.579e-03]
 [-6.470e-03 -1.219e-03]
 [-1.314e-04 -1.882e-02]
 [ 3.779e-03 -1.503e-02]
 [ 5.096e-03 -6.771e-03]
 [ 1.637e-02 -9.941e-03]
 [ 3.747e-03  1.786e-03]
 [-8.756e-03 -1.095e-03]
 [-1.212e-02 -7.522e-03]
 [-5.186e-03 -5.362e-03]
 [-1.980e-03 -5.631e-03]
 [ 1.305e-03  1.520e-03]
 [ 2.041e-02  4.763e-03]
 [ 1.424e-02 -1.341e-03]
 [ 1.573e-02 -1.060e-03]
 [ 1.209e-03  2.100e-03]
 [-1.182e-03  1.769e-03]
 [-1.271e-02 -4.995e-03]
 [-1.870e-02 -1.912e-02]
 [ 1.367e-02  1.218e-04]
 [ 8.574e-03  3.915e-03]
 [ 1.083e-02  1.644e-03]
 [ 7.115e-03  4.403e-04]
 [ 6.456e-03  9.833e-04]
 [ 6.389e-03  9.731e-04]
 [ 5.731e-04 -5.455e-04]
 [ 4.015e-03 -1.279e-03]
 [ 1.146e-03  1.769e-04]
 [-1.711e-03  9.980e-04]
 [-1.562e-02  8.470e-03]
 [-1.837e-02  2.005e-02]
 [-6.628e-03  1.025e-02]
 [-1.823e-03  2.398e-03]
 [-1.212e-03  2.475e-03]
 [-6.023e-04  1.894e-03]
 [-6.075e-04  1.241e-03]
 [ 9.143

2024-06-04 04:37:50.632289: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


2024-06-04 04:37:50.819219: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 7.379e-03 -3.265e-03]
 [ 2.150e-02  8.641e-03]
 [ 5.231e-03  2.558e-02]
 [-8.750e-03  1.977e-02]
 [-7.114e-03  1.277e-02]
 [-5.404e-03  3.706e-03]
 [ 2.828e-09 -1.845e-03]
 [-7.156e-03 -2.913e-02]
 [-1.982e-03 -8.070e-03]
 [-9.309e-03 -2.182e-03]
 [-3.772e-03  5.530e-03]
 [-5.711e-03  1.122e-02]
 [-7.716e-03  1.324e-02]
 [-3.902e-03  7.657e-03]
 [-1.962e-03  5.773e-03]
 [-3.946e-03  1.740e-02]
 [ 3.607e-03  2.978e-02]
 [ 2.301e-03  1.612e-02]
 [ 9.699e-03 -8.279e-03]
 [ 1.515e-02 -4.688e-03]
 [ 1.107e-02  3.056e-03]
 [ 1.083e-02  2.131e-02]
 [-1.788e-03  1.483e-02]
 [-5.404e-03  6.073e-03]
 [-5.463e-03  4.285e-03]
 [-1.834e-03 -1.659e-03]
 [-5.544e-03 -1.062e-02]
 [-1.862e-03 -1.480e-02]
 [-1.227e-02 -2.738e-02]
 [-1.032e-02 -2.817e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiUKGXdvcmtlcl8xMzRfZXBfMTRfMDZfMDZfMjIQxAEY1QEgDzAHKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  18


action sequence:
[[-0.006 -0.007]
 [-0.    -0.012]
 [-0.003 -0.011]
 [-0.002 -0.01 ]
 [ 0.004 -0.007]
 [ 0.004 -0.011]
 [ 0.001 -0.007]
 [ 0.003 -0.007]
 [-0.002 -0.006]
 [ 0.001 -0.002]
 [ 0.007  0.026]
 [ 0.004  0.016]
 [-0.016  0.009]
 [-0.008 -0.005]
 [-0.002 -0.003]
 [-0.002 -0.01 ]
 [ 0.002 -0.014]
 [ 0.     0.   ]]
Episode id: b'EiQKGHdvcmtlcl8xMDBfZXBfMF8wNV8wOV8yMhClARi_ASASMAgqIGIwMzEwNzBjZjRjZGYwYTJlODgzOWExM2JlZDRkN2Zk'
step numbers:  27


2024-06-04 04:37:50.970308: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 1.400e-03 -3.192e-04]
 [ 5.563e-03 -1.268e-03]
 [ 2.956e-02 -5.137e-03]
 [ 2.573e-02 -1.542e-02]
 [ 1.227e-02 -2.737e-02]
 [ 1.174e-02 -2.761e-02]
 [-5.308e-03 -2.953e-02]
 [-1.738e-02 -2.446e-02]
 [-2.958e-02  4.993e-03]
 [-2.827e-02  1.004e-02]
 [-2.767e-02  1.160e-02]
 [-2.406e-02  1.793e-02]
 [-9.248e-03  1.956e-02]
 [-7.634e-03  7.438e-03]
 [ 3.476e-05  1.244e-03]
 [-1.470e-03  3.994e-03]
 [ 3.481e-05  1.246e-03]
 [-1.579e-03  2.637e-04]
 [-1.618e-03 -9.851e-04]
 [-9.667e-03 -9.286e-04]
 [-1.148e-02 -6.794e-04]
 [-3.302e-03  5.330e-04]
 [-3.286e-03  1.817e-03]
 [-1.525e-03  5.401e-03]
 [ 1.075e-04  3.847e-03]
 [-7.164e-05 -2.565e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiMKGHdvcmtlcl8wODhfZXBfNF8wNl8xN18yMhBtGJMBIAQwCSogZDRkNTFjYzE0YzI0OWY0ODA2MTRlMzUwM2FmZThiZDU='
step numbers:  39


2024-06-04 04:37:51.126911: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-5.675e-04 -2.142e-02]
 [ 6.919e-05 -9.909e-03]
 [ 6.134e-04  1.484e-02]
 [ 4.061e-03  2.845e-02]
 [ 7.547e-03  1.134e-02]
 [ 7.393e-03  6.923e-04]
 [ 5.242e-03  1.339e-04]
 [ 4.538e-03 -6.007e-03]
 [ 2.011e-03 -1.570e-02]
 [-1.077e-03 -2.707e-02]
 [-2.356e-03 -2.803e-02]
 [-2.409e-03 -2.441e-02]
 [-2.457e-03 -2.152e-02]
 [-4.533e-03 -1.413e-02]
 [-5.973e-03 -1.627e-02]
 [-5.429e-03 -1.571e-02]
 [-5.581e-03 -1.194e-02]
 [-6.458e-03 -9.902e-03]
 [-3.564e-03 -1.945e-02]
 [ 1.175e-04 -1.683e-02]
 [ 8.187e-04 -1.068e-02]
 [ 7.519e-04 -1.423e-03]
 [-1.171e-04  1.678e-02]
 [ 7.155e-03  2.131e-02]
 [ 1.118e-02  1.282e-02]
 [ 8.781e-03  1.465e-03]
 [ 3.376e-03 -1.098e-02]
 [-5.501e-04 -1.520e-02]
 [-5.823e-03 -2.347e-02]
 [-2.606e-03 -1.464e-02]
 [ 5.614e-05 -8.041e-03]
 [ 2.807e-05 -4.021e-03]
 [ 3.930e-05 -5.629e-03]
 [ 6.176e-05 -8.845e-03]
 [ 5.614e-05 -8.041e-03]
 [ 4.492e-05 -6.433e-03]
 [ 1.684e-05 -2.412e-03]
 [ 5.614e-06 -8.041e-04]
 [ 0.000e+00  0.000e+00]]
Episode

2024-06-04 04:37:51.322560: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  37


2024-06-04 04:37:51.517445: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-6.667e-03 -8.333e-04]
 [-1.000e-02 -4.167e-03]
 [-1.333e-02 -9.167e-03]
 [ 1.167e-02 -6.667e-03]
 [ 5.000e-03 -1.667e-03]
 [-2.713e-02 -1.281e-02]
 [-2.454e-02 -7.190e-03]
 [-1.583e-02  2.196e-08]
 [-5.000e-03 -1.667e-03]
 [-2.000e-02  2.680e-08]
 [-1.667e-03  2.233e-09]
 [ 8.333e-04  3.333e-03]
 [ 2.667e-02  1.374e-02]
 [ 2.764e-02  1.167e-02]
 [ 2.736e-02  1.232e-02]
 [ 2.771e-02  1.148e-02]
 [ 2.770e-02  1.153e-02]
 [ 2.785e-02  1.116e-02]
 [ 2.603e-02  1.491e-02]
 [ 2.498e-02  1.662e-02]
 [ 2.648e-02  1.410e-02]
 [ 2.670e-02  1.367e-02]
 [ 2.578e-02  1.534e-02]
 [ 2.369e-02  1.841e-02]
 [ 1.693e-02  2.477e-02]
 [-4.395e-04  3.000e-02]
 [-1.508e-02  4.459e-03]
 [-1.750e-02 -3.333e-03]
 [-2.083e-02 -1.583e-02]
 [-1.535e-02 -2.577e-02]
 [-1.551e-02 -2.568e-02]
 [-2.312e-02 -1.912e-02]
 [-2.730e-02 -1.243e-02]
 [-2.854e-02 -9.242e-03]
 [ 4.827e-03  1.141e-02]
 [ 2.121e-02  2.121e-02]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiQKGHdvcmtlcl8wMDdfZXBfOF8wNl8wNl8yMhCFARi

action sequence:
[[-6.102e-03  6.181e-03]
 [-3.360e-03  6.992e-03]
 [-9.881e-03  1.376e-02]
 [-3.741e-03  4.305e-03]
 [-9.777e-03  6.271e-03]
 [-9.094e-03  4.516e-03]
 [-5.218e-03  3.304e-05]
 [-1.263e-02  7.342e-03]
 [-2.096e-02  5.040e-03]
 [-1.134e-03  2.073e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiIKGHdvcmtlcl8xMDRfZXBfMV8wNV8wOV8yMhBHGHkgDjAMKiBiMDMxMDcwY2Y0Y2RmMGEyZTg4MzlhMTNiZWQ0ZDdmZA=='
step numbers:  51


2024-06-04 04:37:51.657130: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-5.444e-03 -1.169e-02]
 [-8.256e-03 -1.422e-02]
 [-5.565e-03 -7.227e-03]
 [ 5.688e-09 -2.354e-03]
 [ 1.382e-02  7.499e-03]
 [ 1.165e-02  2.765e-02]
 [-6.204e-03  2.121e-02]
 [-5.444e-03 -4.616e-03]
 [-8.256e-03 -2.313e-03]
 [-5.565e-03 -4.698e-03]
 [-5.614e-03 -2.129e-02]
 [ 3.460e-08 -1.419e-02]
 [-8.515e-03  2.127e-03]
 [-2.032e-02  4.269e-03]
 [-2.955e-03 -7.143e-05]
 [-2.969e-03 -9.788e-03]
 [-8.988e-03 -5.175e-03]
 [-9.113e-03 -5.247e-03]
 [-9.240e-03 -5.320e-03]
 [-3.109e-03 -5.104e-03]
 [-3.123e-03 -1.451e-04]
 [-1.264e-02 -5.617e-03]
 [-3.197e-03 -5.202e-03]
 [-6.440e-03 -5.413e-03]
 [-6.502e-03 -8.009e-03]
 [-6.564e-03 -1.831e-02]
 [-6.627e-03 -1.592e-02]
 [ 1.871e-08 -7.708e-03]
 [ 3.322e-03 -4.818e-03]
 [ 3.306e-03 -9.909e-03]
 [ 3.290e-03 -4.760e-03]
 [-6.596e-03  2.236e-02]
 [-3.322e-03  2.796e-02]
 [ 3.322e-03  2.798e-03]
 [ 1.960e-02 -3.706e-03]
 [ 2.217e-02 -5.849e-03]
 [ 9.283e-03 -9.149e-03]
 [ 3.066e-03 -9.588e-03]
 [-6.146e-03 -2.779e-02]
 [-3.094

2024-06-04 04:37:51.850724: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


step numbers:  15


action sequence:
[[ 0.019  0.023]
 [ 0.029  0.006]
 [ 0.03   0.001]
 [ 0.011 -0.001]
 [ 0.013 -0.011]
 [ 0.007 -0.029]
 [ 0.003 -0.023]
 [-0.008 -0.02 ]
 [-0.005 -0.003]
 [-0.01  -0.001]
 [-0.016  0.008]
 [-0.013  0.01 ]
 [-0.019  0.024]
 [-0.022  0.021]
 [ 0.     0.   ]]
Episode id: b'EiUKGXdvcmtlcl8wNDNfZXBfMTRfMDZfMDZfMjIQmAEYwQEgEjAOKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  42


2024-06-04 04:37:51.999808: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-0.03  -0.005]
 [-0.017  0.006]
 [-0.007  0.002]
 [-0.005 -0.007]
 [-0.005  0.   ]
 [-0.008  0.007]
 [-0.011  0.015]
 [-0.018  0.024]
 [-0.007  0.009]
 [-0.003  0.004]
 [-0.001 -0.001]
 [ 0.006 -0.029]
 [ 0.003 -0.015]
 [-0.01   0.028]
 [-0.007  0.027]
 [-0.003  0.009]
 [-0.01   0.016]
 [-0.006  0.009]
 [-0.    -0.03 ]
 [ 0.001 -0.006]
 [-0.01   0.013]
 [-0.01   0.013]
 [-0.011  0.017]
 [-0.009  0.015]
 [-0.006  0.011]
 [ 0.006 -0.029]
 [-0.007 -0.025]
 [-0.005 -0.001]
 [-0.011  0.013]
 [-0.006  0.01 ]
 [ 0.002  0.021]
 [ 0.004  0.014]
 [ 0.002  0.016]
 [ 0.001  0.001]
 [ 0.006 -0.029]
 [ 0.004 -0.03 ]
 [ 0.005 -0.03 ]
 [ 0.008 -0.029]
 [ 0.016 -0.025]
 [ 0.017 -0.025]
 [ 0.017 -0.025]
 [ 0.     0.   ]]
Episode id: b'EiIKGHdvcmtlcl8wOTBfZXBfNV8wNV8xN18yMhAfGDIgAjAPKiA3NWRlMWJlNGU1MTcwZTRiOGM2MTBmNThjNzZiNjUwMg=='
step numbers:  20


2024-06-04 04:37:52.201260: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-1.773e-03  7.710e-03]
 [-5.366e-03  5.508e-03]
 [-5.434e-03  6.878e-04]
 [-3.662e-03  1.009e-03]
 [-3.693e-03  1.018e-03]
 [-3.725e-03  2.678e-03]
 [-1.875e-03 -3.072e-04]
 [-5.673e-03  7.360e-04]
 [-5.747e-03  7.457e-04]
 [-1.933e-03  1.371e-03]
 [-1.941e-03 -1.991e-03]
 [-1.950e-03  1.376e-03]
 [-6.984e-09  3.376e-03]
 [-6.931e-09  3.376e-03]
 [-1.958e-03  1.397e-03]
 [-1.967e-03 -2.924e-04]
 [-1.976e-03  1.405e-03]
 [-1.984e-03  1.412e-03]
 [ 9.835e-03 -5.312e-03]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiUKGHdvcmtlcl8xNTZfZXBfNF8wNl8wNl8yMhCMARicASAJMOgHKiBmNTI1ODUyODdhMTU3NmI4NWRmYmMyOTliNDk4MTFmYw=='
step numbers:  17


2024-06-04 04:37:52.361643: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[-1.354e-02 -8.802e-03]
 [-1.693e-02 -5.417e-03]
 [-1.286e-02  1.255e-09]
 [-4.062e-03 -1.354e-03]
 [ 0.000e+00 -6.771e-03]
 [-5.551e-17 -2.708e-03]
 [ 5.551e-17 -3.385e-03]
 [ 1.219e-02 -7.448e-03]
 [ 6.771e-04  5.791e-10]
 [-2.167e-02 -1.563e-08]
 [-1.828e-02  5.417e-03]
 [-9.479e-03  1.016e-02]
 [-3.385e-03  4.062e-03]
 [ 2.031e-03  3.385e-03]
 [ 1.354e-03  1.354e-03]
 [ 5.120e-11 -6.771e-04]
 [ 0.000e+00  0.000e+00]]
Episode id: b'EiMKGHdvcmtlcl8wMzlfZXBfMl8wNl8xN18yMhAAGCIgADDpByogZDRkNTFjYzE0YzI0OWY0ODA2MTRlMzUwM2FmZThiZDU='
step numbers:  35


2024-06-04 04:37:52.532802: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


action sequence:
[[ 2.694e-03 -4.873e-05]
 [ 2.834e-02  9.830e-03]
 [ 2.944e-02  5.763e-03]
 [ 2.974e-02  3.963e-03]
 [ 2.998e-02  1.010e-03]
 [ 2.971e-02 -4.153e-03]
 [ 1.412e-02 -3.915e-03]
 [ 4.315e-03 -3.197e-03]
 [ 2.673e-03 -2.525e-03]
 [ 1.241e-02 -3.054e-04]
 [ 1.069e-02  2.759e-03]
 [ 8.019e-03  7.001e-03]
 [ 5.854e-03  6.404e-03]
 [ 2.155e-03  4.109e-03]
 [ 2.249e-03  8.873e-03]
 [-1.395e-03  7.240e-03]
 [-7.869e-03  2.084e-02]
 [-6.379e-03  2.096e-02]
 [-3.878e-03  1.667e-02]
 [-1.915e-03  9.888e-03]
 [ 6.349e-05  3.031e-03]
 [-1.453e-03  6.831e-03]
 [ 6.583e-04  6.013e-03]
 [ 7.662e-03  1.189e-02]
 [ 9.208e-03  1.458e-02]
 [ 2.792e-03  9.259e-03]
 [ 2.354e-03  1.348e-02]
 [ 1.206e-03  8.222e-03]
 [ 1.743e-03  9.327e-03]
 [ 1.139e-03  5.212e-03]
 [ 5.628e-04  2.305e-03]
 [ 1.249e-05  5.965e-04]
 [-6.657e-03  2.864e-03]
 [-8.287e-03  3.144e-03]
 [ 0.000e+00  0.000e+00]]
global action min: [-0.03 -0.03]
global action max: [0.03 0.03]


2024-06-04 04:37:52.714980: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
