In [1]:
import json

# Assume you have a list of dictionaries
data = [{"name": "John", "age": 30}, {"name": "Mike", "age": 25}]


def write_jsonl(data, filename):
    with open(filename, "w") as f:
        for element in data:
            # Write as a JSON formatted string
            f.write(json.dumps(element) + "\n")


write_jsonl(data, "output.jsonl")

In [8]:
import tensorflow as tf
import numpy as np

data = np.arange(100)
data = data.reshape(-1, 1)
ds1 = tf.data.Dataset.from_tensor_slices(data)

In [9]:
list(ds1.as_numpy_iterator())

2024-06-17 12:31:34.305240: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12]),
 array([13]),
 array([14]),
 array([15]),
 array([16]),
 array([17]),
 array([18]),
 array([19]),
 array([20]),
 array([21]),
 array([22]),
 array([23]),
 array([24]),
 array([25]),
 array([26]),
 array([27]),
 array([28]),
 array([29]),
 array([30]),
 array([31]),
 array([32]),
 array([33]),
 array([34]),
 array([35]),
 array([36]),
 array([37]),
 array([38]),
 array([39]),
 array([40]),
 array([41]),
 array([42]),
 array([43]),
 array([44]),
 array([45]),
 array([46]),
 array([47]),
 array([48]),
 array([49]),
 array([50]),
 array([51]),
 array([52]),
 array([53]),
 array([54]),
 array([55]),
 array([56]),
 array([57]),
 array([58]),
 array([59]),
 array([60]),
 array([61]),
 array([62]),
 array([63]),
 array([64]),
 array([65]),
 array([66]),
 array([67]),
 array([68]),
 array([69]),
 array([70]),
 array([71]),
 a

In [10]:
type(ds1)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [11]:
train_data, val_data = tf.keras.utils.split_dataset(
    ds1, left_size=0.8, right_size=0.2, shuffle=True
)

2024-06-17 12:31:41.639709: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [12]:
list(train_data.as_numpy_iterator())

2024-06-17 12:32:01.691422: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


[(51,),
 (38,),
 (25,),
 (69,),
 (75,),
 (76,),
 (34,),
 (4,),
 (59,),
 (39,),
 (64,),
 (17,),
 (48,),
 (27,),
 (98,),
 (60,),
 (43,),
 (5,),
 (36,),
 (66,),
 (89,),
 (26,),
 (15,),
 (68,),
 (23,),
 (50,),
 (21,),
 (28,),
 (40,),
 (12,),
 (33,),
 (58,),
 (93,),
 (52,),
 (10,),
 (32,),
 (57,),
 (55,),
 (13,),
 (22,),
 (31,),
 (71,),
 (8,),
 (54,),
 (95,),
 (37,),
 (85,),
 (77,),
 (44,),
 (72,),
 (99,),
 (46,),
 (20,),
 (63,),
 (78,),
 (74,),
 (92,),
 (56,),
 (0,),
 (45,),
 (16,),
 (47,),
 (24,),
 (62,),
 (97,),
 (9,),
 (61,),
 (86,),
 (49,),
 (82,),
 (2,),
 (79,),
 (70,),
 (14,),
 (41,),
 (53,),
 (29,),
 (83,),
 (81,),
 (65,)]